// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PEALSystem.Kimbemba.Configuracoes;

namespace PEALSystem.Kimbemba.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PEALSystem.Kimbemba.Models.CodigoBarra", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnName("Codigo")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CodigoAEN")
                        .IsRequired()
                        .HasColumnName("CodigoAEN")
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("Data")
                        .HasColumnName("Data")
                        .HasColumnType("date");

                    b.Property<int>("Numero")
                        .HasColumnName("Numero")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoAEN")
                        .IsUnique();

                    b.ToTable("codigo_barras");
                });
#pragma warning restore 612, 618
        }
    }
}
